# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::394356247783:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::394356247783:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-D3A5UL8SSK5U
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-29T03:22:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-29T03:22:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1301"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dc752648-9803-43f4-ab29-2cd40087615c
